<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	  <Title>VictorPedroso.AddSecurityJWT</Title>
	  <Authors>Victor Pedroso</Authors>
	  <Description>The package adds the jwt configuration in swagger, authentication in the application and creates the Admin, Manager and Client policies</Description>
	  <PackageReleaseNotes>Add a new feature</PackageReleaseNotes>
	  <PackageId>VictorPedroso.AddSecurityJWT</PackageId>
	  <PackageTags>JWT, security, swagger security</PackageTags>
	  <Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="7.2.0" />
  </ItemGroup>

</Project>
