<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.7.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="VictorPedroso.AddSecurityJWT" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechSolutions.Infrastructure.Data\TechSolutions.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\TechSolutions.Infrastructure.IoC\TechSolutions.Infrastructure.IoC.csproj" />
  </ItemGroup>

</Project>
